name: Docker Image

on:
  push:
    branches: [ master ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ipbhalle/metfragweb

      - name: Maven Build Cache for Docker
        uses: actions/cache@v4
        with:
          path: maven-cache
          key: ${{ runner.os }}-maven-cache-${{ hashFiles('**/pom.xml') }}

      - name: Inject Maven Build Cache into Docker
        uses: reproducible-containers/buildkit-cache-dance@v3.2.0
        with:
          cache-map: |
            {
              "maven-cache": "/root/.m2"
            }

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          file: Dockerfile-REST
          tags: ipbhalle/metfragrest:latest
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max